name: Netlify PR Preview & Main Deploy

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify (Preview)
        id: netlify-deploy
        uses: jsmrcaga/action-netlify-deploy@v2.3.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: false
          build_directory: dist

      - name: Save Deploy ID
        run: echo "NETLIFY_DEPLOY_ID=${{ steps.netlify-deploy.outputs.deploy_id }}" >> $GITHUB_ENV

      - name: Add PR comment with preview URL
        uses: mshick/add-pr-comment@v2
        with:
          message: "✅ [Предпросмотр доступен](${{ steps.netlify-deploy.outputs.NETLIFY_URL }})"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  check-deploy:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Check if deployment was successful
        run: |
          if [ "${{ needs.deploy-preview.outputs.NETLIFY_DEPLOY_STATUS }}" != "success" ]; then
            echo "❌ Ошибка деплоя! Запрещаем мердж!"
            exit 1
          fi

  delete-preview:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview deployment
        run: |
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          "https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys/${{ env.NETLIFY_DEPLOY_ID }}"

  deploy-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project for production
        run: npm run build

      - name: Deploy to Netlify (Main)
        uses: jsmrcaga/action-netlify-deploy@v2.3.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist
